# Configuration for CSRNet Counting

# File settings
image_dir: "/mnt/towbin.data/shared/smarin/analysis/lifespan_20240404-20240605/raw"
output_dir: "/mnt/towbin.data/shared/smarin/analysis/lifespan_20240404-20240605/analysis/csrnet_count"

channels: [2]
augment_contrast: False

# Logging settings
log_file: "eggcount.log"

# GPU settings
use_gpu: true
gpu_device: [0,1]

# Model settings
model_path: "/mnt/towbin.data/shared/smarin/models/brightfield_egg/csrnet_full-thresh30%-dist25-mindist20-sigma10/model_epoch_590_f1_0.6069.pth"
batch_size: 4
num_workers: 30

tile_size: 1024
overlap: 256

# Count settings
threshold: 0.3
min_size: 20
min_distance: 20
match_distance: 35

# Database settings
create_json: False
save_visual: False